package com.dlunaunizar.bobitos.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Sistema visual de Bobitos: estilo «Minimal moderno · Verde azulado».
// Un único acento verde azulado (teal) sobre neutros cálidos; secundario y terciario
// contenidos para que el acento mande. El error es un carmesí distinto del acento.
// Valores contrastados a mano (AA) siguiendo las posiciones tonales de Material 3.

// --- Claro ---
internal val primaryLight = Color(0xFF0F766E)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFCFF3EE)
internal val onPrimaryContainerLight = Color(0xFF00201C)
internal val secondaryLight = Color(0xFF4B5F5C)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFDBE7E4)
internal val onSecondaryContainerLight = Color(0xFF0B1F1C)
internal val tertiaryLight = Color(0xFF3F5C77)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFD6E4F2)
internal val onTertiaryContainerLight = Color(0xFF0A1B29)
internal val errorLight = Color(0xFFB3261E)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFF9DEDC)
internal val onErrorContainerLight = Color(0xFF410E0B)
internal val backgroundLight = Color(0xFFFBFAF8)
internal val onBackgroundLight = Color(0xFF1B1B19)
internal val surfaceLight = Color(0xFFFBFAF8)
internal val onSurfaceLight = Color(0xFF1B1B19)
internal val surfaceVariantLight = Color(0xFFE6E3DE)
internal val onSurfaceVariantLight = Color(0xFF494844)
internal val outlineLight = Color(0xFF7A7873)
internal val outlineVariantLight = Color(0xFFCBC8C2)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF5F3F0)
internal val surfaceContainerLight = Color(0xFFEFEDE9)
internal val surfaceContainerHighLight = Color(0xFFEAE7E2)
internal val surfaceContainerHighestLight = Color(0xFFE4E1DB)
internal val inverseSurfaceLight = Color(0xFF303331)
internal val inverseOnSurfaceLight = Color(0xFFF1EFEB)
internal val inversePrimaryLight = Color(0xFF5FD9CC)
internal val scrimLight = Color(0xFF000000)

// --- Oscuro (carbón neutro cálido, no negro puro) ---
internal val primaryDark = Color(0xFF5FD9CC)
internal val onPrimaryDark = Color(0xFF003731)
internal val primaryContainerDark = Color(0xFF005048)
internal val onPrimaryContainerDark = Color(0xFFCFF3EE)
internal val secondaryDark = Color(0xFFB6C9C5)
internal val onSecondaryDark = Color(0xFF213531)
internal val secondaryContainerDark = Color(0xFF33413E)
internal val onSecondaryContainerDark = Color(0xFFDBE7E4)
internal val tertiaryDark = Color(0xFFA9C7E3)
internal val onTertiaryDark = Color(0xFF0F2A3F)
internal val tertiaryContainerDark = Color(0xFF274056)
internal val onTertiaryContainerDark = Color(0xFFD6E4F2)
internal val errorDark = Color(0xFFF2B8B5)
internal val onErrorDark = Color(0xFF601410)
internal val errorContainerDark = Color(0xFF8C1D18)
internal val onErrorContainerDark = Color(0xFFF9DEDC)
internal val backgroundDark = Color(0xFF141513)
internal val onBackgroundDark = Color(0xFFE5E3DE)
internal val surfaceDark = Color(0xFF141513)
internal val onSurfaceDark = Color(0xFFE5E3DE)
internal val surfaceVariantDark = Color(0xFF494844)
internal val onSurfaceVariantDark = Color(0xFFCBC8C2)
internal val outlineDark = Color(0xFF94918B)
internal val outlineVariantDark = Color(0xFF494844)
internal val surfaceContainerLowestDark = Color(0xFF0E0F0D)
internal val surfaceContainerLowDark = Color(0xFF1C1D1A)
internal val surfaceContainerDark = Color(0xFF202220)
internal val surfaceContainerHighDark = Color(0xFF2B2C29)
internal val surfaceContainerHighestDark = Color(0xFF363734)
internal val inverseSurfaceDark = Color(0xFFE5E3DE)
internal val inverseOnSurfaceDark = Color(0xFF303331)
internal val inversePrimaryDark = Color(0xFF0F766E)
internal val scrimDark = Color(0xFF000000)
