package com.dlunaunizar.bobitos.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Sistema visual de Bobitos: identidad cálida «hogar».
// Semillas de marca: primario mandarina/caramelo · secundario verde salvia · terciario miel.
// El error es un carmesí deliberadamente distinto del naranja primario.
// Valores contrastados a mano (AA) siguiendo las posiciones tonales de Material 3.

// --- Claro ---
internal val primaryLight = Color(0xFF8A5100)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDDB7)
internal val onPrimaryContainerLight = Color(0xFF2C1600)
internal val secondaryLight = Color(0xFF4E6355)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFD0E8DB)
internal val onSecondaryContainerLight = Color(0xFF0B1F17)
internal val tertiaryLight = Color(0xFF7A5900)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFFFE08B)
internal val onTertiaryContainerLight = Color(0xFF261A00)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF8F6)
internal val onBackgroundLight = Color(0xFF221A17)
internal val surfaceLight = Color(0xFFFFF8F6)
internal val onSurfaceLight = Color(0xFF221A17)
internal val surfaceVariantLight = Color(0xFFF4DED2)
internal val onSurfaceVariantLight = Color(0xFF52443A)
internal val outlineLight = Color(0xFF847469)
internal val outlineVariantLight = Color(0xFFD6C3B6)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFFF1E8)
internal val surfaceContainerLight = Color(0xFFFCEBE0)
internal val surfaceContainerHighLight = Color(0xFFF6E5DB)
internal val surfaceContainerHighestLight = Color(0xFFF0E0D5)
internal val inverseSurfaceLight = Color(0xFF382E29)
internal val inverseOnSurfaceLight = Color(0xFFFFEDE2)
internal val inversePrimaryLight = Color(0xFFFFB868)
internal val scrimLight = Color(0xFF000000)

// --- Oscuro (carbón cálido, no negro puro) ---
internal val primaryDark = Color(0xFFFFB868)
internal val onPrimaryDark = Color(0xFF492900)
internal val primaryContainerDark = Color(0xFF683D00)
internal val onPrimaryContainerDark = Color(0xFFFFDDB7)
internal val secondaryDark = Color(0xFFB4CCBF)
internal val onSecondaryDark = Color(0xFF20352B)
internal val secondaryContainerDark = Color(0xFF364B40)
internal val onSecondaryContainerDark = Color(0xFFD0E8DB)
internal val tertiaryDark = Color(0xFFEEC148)
internal val onTertiaryDark = Color(0xFF412D00)
internal val tertiaryContainerDark = Color(0xFF5C4200)
internal val onTertiaryContainerDark = Color(0xFFFFE08B)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A120E)
internal val onBackgroundDark = Color(0xFFF1DFD5)
internal val surfaceDark = Color(0xFF1A120E)
internal val onSurfaceDark = Color(0xFFF1DFD5)
internal val surfaceVariantDark = Color(0xFF52443A)
internal val onSurfaceVariantDark = Color(0xFFD6C3B6)
internal val outlineDark = Color(0xFF9F8D80)
internal val outlineVariantDark = Color(0xFF52443A)
internal val surfaceContainerLowestDark = Color(0xFF140C08)
internal val surfaceContainerLowDark = Color(0xFF221A16)
internal val surfaceContainerDark = Color(0xFF271E19)
internal val surfaceContainerHighDark = Color(0xFF322824)
internal val surfaceContainerHighestDark = Color(0xFF3D332E)
internal val inverseSurfaceDark = Color(0xFFF1DFD5)
internal val inverseOnSurfaceDark = Color(0xFF382E29)
internal val inversePrimaryDark = Color(0xFF8A5100)
internal val scrimDark = Color(0xFF000000)
